### ISSUE TITLE
This plugin not working with laravel 5.4+ version

### ISSUE THREAD

**Issue by bipinm25** [princealikhan/laravel-mautic-api#6]
I tried to install this plugin on laravel 5.4 but it throws the error remove laravel 5.4. How can i install this plugin in laravel 5.4.

**Comment by princealikhan** [comment]
I added support for new version can you try now and do let me know if you face any other issues.
Thanks

**Comment by bipinm25** [comment]
Hi, That issue is solved thanks.  Now i tried to add a new contact but it throws this error 
" _Trying to get property of non-object  in Mautic.php (line 79)_ ". and i check that line "  `$expirationStatus = $this->factory->checkExpirationTime($consumer->expires);` ". That `$consumer->expirese` fetch data from the table `mautic_consumer`. That table is empty. From where should i get data for that table. Only thing in my hand is client_id and secret key.

**Comment by princealikhan** [comment]
you need to create a map of your application user id and mautic user id and
store it here in order to create or update.


*Thanks & Regards,*
*Prince Ali Khan*
*Phone, *+91 99 40 619658
princealikhan08@gmail.com || princealikhan08@hotmail.com
*Facebook <http://www.facebook.com/princekhanprofile> || Twitter
<https://twitter.com/princeprofile> *
